# Generated by Django 5.1.4 on 2025-12-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('term', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('closing_date', models.DateField()),
                ('message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Registration Status',
            },
        ),
    ]
