# Generated by Django 5.1.4 on 2025-12-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_nurseryregistration_primaryregistration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurseryregistration',
            options={'ordering': ['-year', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='primaryregistration',
            options={'ordering': ['-year', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='secondaryregistration',
            options={'ordering': ['-year', '-created_at']},
        ),
        migrations.AddField(
            model_name='nurseryregistration',
            name='term',
            field=models.CharField(default='Term 1', max_length=100),
        ),
        migrations.AddField(
            model_name='nurseryregistration',
            name='year',
            field=models.CharField(default='2025', max_length=4),
        ),
        migrations.AddField(
            model_name='primaryregistration',
            name='term',
            field=models.CharField(default='Term 1', max_length=100),
        ),
        migrations.AddField(
            model_name='primaryregistration',
            name='year',
            field=models.CharField(default='2025', max_length=4),
        ),
        migrations.AddField(
            model_name='secondaryregistration',
            name='term',
            field=models.CharField(default='Term 1', max_length=100),
        ),
        migrations.AddField(
            model_name='secondaryregistration',
            name='year',
            field=models.CharField(default='2025', max_length=4),
        ),
    ]
