# Generated by Django 5.1.4 on 2025-12-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_nurseryregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseryregistration',
            name='birth_certificate',
            field=models.FileField(blank=True, upload_to='registrations/nursery/birth_certificates/'),
        ),
        migrations.AddField(
            model_name='nurseryregistration',
            name='payment_receipt',
            field=models.FileField(blank=True, upload_to='registrations/nursery/receipts/'),
        ),
        migrations.AddField(
            model_name='nurseryregistration',
            name='previous_report',
            field=models.FileField(blank=True, upload_to='registrations/nursery/reports/'),
        ),
        migrations.AddField(
            model_name='nurseryregistration',
            name='recommendation_letter',
            field=models.FileField(blank=True, upload_to='registrations/nursery/recommendations/'),
        ),
        migrations.AddField(
            model_name='primaryregistration',
            name='birth_certificate',
            field=models.FileField(blank=True, upload_to='registrations/primary/birth_certificates/'),
        ),
        migrations.AddField(
            model_name='primaryregistration',
            name='payment_receipt',
            field=models.FileField(blank=True, upload_to='registrations/primary/receipts/'),
        ),
        migrations.AddField(
            model_name='primaryregistration',
            name='previous_transcripts',
            field=models.FileField(blank=True, upload_to='registrations/primary/transcripts/'),
        ),
        migrations.AddField(
            model_name='primaryregistration',
            name='recommendation_letter',
            field=models.FileField(blank=True, upload_to='registrations/primary/recommendations/'),
        ),
        migrations.AddField(
            model_name='primaryregistration',
            name='transfer_certificate',
            field=models.FileField(blank=True, upload_to='registrations/primary/transfer_certificates/'),
        ),
        migrations.AddField(
            model_name='secondaryregistration',
            name='birth_certificate',
            field=models.FileField(blank=True, upload_to='registrations/secondary/birth_certificates/'),
        ),
        migrations.AddField(
            model_name='secondaryregistration',
            name='payment_receipt',
            field=models.FileField(blank=True, upload_to='registrations/secondary/receipts/'),
        ),
        migrations.AddField(
            model_name='secondaryregistration',
            name='previous_transcripts',
            field=models.FileField(blank=True, upload_to='registrations/secondary/transcripts/'),
        ),
        migrations.AddField(
            model_name='secondaryregistration',
            name='recommendation_letter',
            field=models.FileField(blank=True, upload_to='registrations/secondary/recommendations/'),
        ),
        migrations.AddField(
            model_name='secondaryregistration',
            name='transfer_certificate',
            field=models.FileField(blank=True, upload_to='registrations/secondary/transfer_certificates/'),
        ),
    ]
