# Generated by Django 5.1.4 on 2025-12-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_alter_nurseryregistration_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseryregistration',
            name='payment_receipt',
            field=models.FileField(default='temp.pdf', upload_to='registrations/nursery/receipts/'),
        ),
        migrations.AlterField(
            model_name='primaryregistration',
            name='payment_receipt',
            field=models.FileField(default='temp.pdf', upload_to='registrations/primary/receipts/'),
        ),
        migrations.AlterField(
            model_name='secondaryregistration',
            name='payment_receipt',
            field=models.FileField(default='temp.pdf', upload_to='registrations/secondary/receipts/'),
        ),
    ]
