# Generated by Django 5.1.4 on 2025-12-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_alter_nurseryregistration_payment_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationstatus',
            name='term',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=100),
        ),
    ]
