# Generated by Django 5.1.4 on 2026-01-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_alter_registrationstatus_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(default="We're Hiring", max_length=200)),
                ('description', models.TextField()),
                ('positions', models.TextField(help_text='Comma-separated list of positions')),
                ('deadline', models.DateField()),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('application_email', models.EmailField(default='info@stlawrenceacademy.edu', max_length=254)),
                ('location', models.CharField(default='Hai Referendum, Juba', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Hiring Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
