# Generated by Django 5.1.15 on 2026-04-14 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_add_campus_visit_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NurseryRegistration',
        ),
        migrations.DeleteModel(
            name='PrimaryRegistration',
        ),
        migrations.DeleteModel(
            name='SecondaryRegistration',
        ),
    ]
