# Generated by Django 5.1.4 on 2025-12-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_image_url_blogpost_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.IntegerField(default=5, help_text='Estimated reading time in minutes'),
        ),
    ]
