# Generated by Django 5.1.4 on 2026-04-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Academics', 'Academics'), ('Sports', 'Sports'), ('Events', 'Events'), ('Announcements', 'Announcements'), ('Achievements', 'Achievements'), ('Arts & Culture', 'Arts & Culture'), ('Health & Wellness', 'Health & Wellness'), ('Community', 'Community'), ('Alumni', 'Alumni'), ('Education & Training', 'Education & Training'), ('Life Skills', 'Life Skills'), ('Opportunities', 'Opportunities'), ('General', 'General'), ('Other', 'Other')], default='General', max_length=50),
        ),
    ]
