# Generated by Django 5.1.4 on 2026-04-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('reviewer_type', models.CharField(choices=[('Parent', 'Parent'), ('Student', 'Student'), ('Alumni', 'Alumni'), ('Staff', 'Staff'), ('Visitor', 'Visitor'), ('Other', 'Other')], default='Other', max_length=20)),
                ('rating', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
