# Generated by Django 5.1.4 on 2025-12-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='section',
            field=models.CharField(choices=[('all', 'All Sections'), ('nursery', 'Nursery School'), ('primary', 'Primary School'), ('secondary', 'Secondary School'), ('pta', 'PTA')], max_length=50),
        ),
    ]
