# Generated by Django 5.1.15 on 2026-04-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='section',
            field=models.CharField(choices=[('director', 'Leadership'), ('admin', 'Admin'), ('nursery', 'Nursery School'), ('primary', 'Primary School'), ('secondary', 'Secondary School'), ('pta', 'PTA')], max_length=50),
        ),
    ]
