# Generated by Django 5.1.4 on 2025-12-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('graduation_year', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.TextField()),
                ('full_desc', models.TextField()),
                ('image', models.ImageField(upload_to='alumni/')),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Alumni',
                'ordering': ['order', 'graduation_year', 'name'],
            },
        ),
    ]
