# Generated by Django 5.1.4 on 2026-04-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniStorySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('graduation_year', models.CharField(max_length=50)),
                ('current_role', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('story', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Story Submission',
                'verbose_name_plural': 'Story Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
