# Generated by Django 5.1.4 on 2026-04-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumnistorysubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumniStorySubmission',
        ),
        migrations.AddField(
            model_name='alumni',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='full_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alumni/'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='short_desc',
            field=models.TextField(blank=True),
        ),
    ]
