# Generated by Django 5.1.4 on 2026-04-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleader',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
