# Generated by Django 5.1.4 on 2026-04-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_alter_studentleader_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='leadership/'),
        ),
    ]
